from django.urls import path
from base.views import *
from base.employee_service_views import *
# from .models import register_computer

urlpatterns = [
    path("all_employees/", AllEmployeeApiView.as_view()),
    path("info-employee/", InfoEmployeeApiView.as_view()),
    path("due-soon-employees/", DueSoonEmployeePPEApiView.as_view()),
    path("import-employees/", EmployeeImportExcelApiView.as_view()),
    path("verify-employee-face/<slug:slug>", EmployeeFaceVerifyApiView.as_view()),
    path("detect-face-boxes/", EmployeeFaceDetectBoxesApiView.as_view()),
    path("filter-data/", FilterDataApiView.as_view()),
    path("ppe-arrivals/", PPEArrivalListCreateApiView.as_view()),
    path("statistics/ppe/", PPEStatisticsApiView.as_view()),
    path("statistics/ppe-arrival-details/", PPEStatisticsArrivalDetailsApiView.as_view()),
    path("statistics/ppe-issued-details/", PPEStatisticsIssuedDetailsApiView.as_view()),
    path("all-items/", AllItemsApiView.as_view()),
    path("item-history-users/", ItemHistoryUsersApiView.as_view()),
    path("item-view/<slug:slug>", ItemDetailApiView.as_view()),
    path("add-item/<slug:slug>", ItemAddApiView.as_view()),
    path("item-stock-check/", ItemStockCheckApiView.as_view()),
    path("item-available-sizes/<int:product_id>/", ItemAvailableSizesApiView.as_view()),
    path("item-verify-image/<slug:slug>", ItemVerifyImageApiView.as_view()),
    path("item-delete/<slug:slug>", ItemDeleteApiView.as_view()),
    path("pending-issue/<int:pk>/", PendingIssueDetailApiView.as_view()),
    path("pending-issue/<int:pk>/confirm/", PendingIssueConfirmApiView.as_view()),
    path("pending-issue/<int:pk>/confirm-direct/", PendingIssueDirectConfirmApiView.as_view()),
    path("pending-issue/employee/<int:employee_id>/", PendingIssueForEmployeeApiView.as_view()),
    path("issue-qr/<uuid:token>/", IssueQRCodeDetailApiView.as_view()),
    path("employees/face-id-exemption/", EmployeeFaceIdExemptionApiView.as_view()),
    path("employees/<slug:employee_slug>/face-id-exemption/", EmployeeFaceIdExemptionApiView.as_view()),
    path("employees/<int:employee_id>/face-id-exemption/", EmployeeFaceIdExemptionApiView.as_view()),
    path("settings/departments/", SettingsDepartmentListCreateApiView.as_view()),
    path("settings/departments/<int:pk>/", SettingsDepartmentDetailApiView.as_view()),
    path("settings/sections/", SettingsSectionListCreateApiView.as_view()),
    path("settings/sections/<int:pk>/", SettingsSectionDetailApiView.as_view()),
    path("settings/employee-positions/", SettingsEmployeePositionListApiView.as_view()),
    path("settings/ppe-products/", SettingsPPEProductListCreateApiView.as_view()),
    path("settings/ppe-products/<int:pk>/", SettingsPPEProductDetailApiView.as_view()),
    path("settings/ppe-department-rules/", SettingsPPEDepartmentRuleListCreateApiView.as_view()),
    path("settings/ppe-department-rules/<int:pk>/", SettingsPPEDepartmentRuleDetailApiView.as_view()),
    path("settings/responsible-persons/", SettingsResponsiblePersonListCreateApiView.as_view()),
    path("settings/responsible-persons/<int:pk>/", SettingsResponsiblePersonDetailApiView.as_view()),
    
    # Employee Service API endpoints
    path("employee-service/departments/", EmployeeServiceDepartmentListApiView.as_view()),
    path("employee-service/departments/<int:department_id>/", EmployeeServiceDepartmentDetailApiView.as_view()),
    path("employee-service/sections/", EmployeeServiceSectionListApiView.as_view()),
    path("employee-service/sections/<int:section_id>/", EmployeeServiceSectionDetailApiView.as_view()),
    path("employee-service/media-proxy/", EmployeeServiceMediaProxyApiView.as_view()),
    path("employee-service/employees/", EmployeeServiceEmployeeListApiView.as_view()),
    path("employee-service/employees/<slug:slug>/", EmployeeServiceEmployeeDetailApiView.as_view()),

]
