"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR.parent / '.env')
load_dotenv(BASE_DIR / '.env')


def _normalize_public_base_url(raw_value, fallback):
    value = (raw_value or fallback).strip().rstrip('/')
    parsed = urlparse(value)
    if not parsed.scheme or not parsed.hostname:
        raise ValueError('PUBLIC_BASE_URL must include scheme and hostname, for example https://192.168.101.6')
    return value


def _build_public_url(base_url, port):
    parsed = urlparse(base_url)
    return f'{parsed.scheme}://{parsed.hostname}:{port}'


def _with_http_and_https(url):
    parsed = urlparse(url)
    http_url = f'http://{parsed.hostname}:{parsed.port}'
    https_url = f'https://{parsed.hostname}:{parsed.port}'
    return [http_url, https_url]


PUBLIC_BASE_URL = _normalize_public_base_url(
    os.environ.get('PUBLIC_BASE_URL', ''),
    'https://192.168.101.6',
)
BACKEND_PORT = int(os.environ.get('BACKEND_PORT', '8050'))
FRONTEND_PORT = int(os.environ.get('FRONTEND_PORT', '6060'))
EMPLOYEE_SERVICE_PORT = int(os.environ.get('EMPLOYEE_SERVICE_PORT', '5000'))
PUBLIC_HOST = urlparse(PUBLIC_BASE_URL).hostname
FRONTEND_PUBLIC_URL = _build_public_url(PUBLIC_BASE_URL, FRONTEND_PORT)
BACKEND_PUBLIC_URL = _build_public_url(PUBLIC_BASE_URL, BACKEND_PORT)
EMPLOYEE_SERVICE_PUBLIC_URL_DEFAULT = _build_public_url(PUBLIC_BASE_URL, EMPLOYEE_SERVICE_PORT)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ahl8&d=hrn@lp!hr0l87u#gf+pk&75!l2*o8$i#4uu&0l-copz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [PUBLIC_HOST, "localhost", "127.0.0.1"]

if DEBUG:
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'base',
    'users',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    'drf_spectacular',
    'drf_spectacular_sidecar',
    'simple_history',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'base.middleware.CurrentUserMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'base.middleware.SimpleHistoryMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.ExpiringTokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

TOKEN_SESSION_TTL_SECONDS = int(os.environ.get('TOKEN_SESSION_TTL_SECONDS', '7200'))
SESSION_COOKIE_AGE = TOKEN_SESSION_TTL_SECONDS
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

database_engine = os.environ.get('DJANGO_DB_ENGINE', 'sqlite').lower()


if database_engine == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'tb_data'),
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'bnpz!@#'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }


LOGGING = {
    'version': 1, 
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ORIGIN_WHITELIST = (
    'http://localhost:5175',
    'http://127.0.0.1:8005',
    f'http://{PUBLIC_HOST}:{FRONTEND_PORT}',
)

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5175',
    'https://localhost:5175',
    *_with_http_and_https(FRONTEND_PUBLIC_URL),
    "http://127.0.0.1:8005",
    "https://127.0.0.1:8005",
    *_with_http_and_https(BACKEND_PUBLIC_URL),
    # 'https://bnpz.uz',
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost(:\d+)?$",
    r"^https?://127\.0\.0\.1(:\d+)?$",
    r"^https?://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$",
    r"^https?://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$",
    r"^https?://172\.(1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}(:\d+)?$",
]

CORS_ALLOW_ALL_ORIGINS = False

CSRF_TRUSTED_ORIGINS = [
    'https://localhost:5175',
    'https://127.0.0.1:5175',
    FRONTEND_PUBLIC_URL,
    'https://localhost:8005',
    'https://127.0.0.1:8005',
    BACKEND_PUBLIC_URL,
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

if DEBUG:

    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

else:

    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


FACE_ID_DIRECT_LOGIN_ENABLED = _env_bool('FACE_ID_DIRECT_LOGIN_ENABLED', False)
FACE_ID_LIVE_BURST_MOTION_THRESHOLD = float(os.environ.get('FACE_ID_LIVE_BURST_MOTION_THRESHOLD', '1.6'))
FACE_ID_LIVE_BURST_MIN_FRAMES = int(os.environ.get('FACE_ID_LIVE_BURST_MIN_FRAMES', '8'))
FACE_ID_BLINK_SCORE_DROP_THRESHOLD = float(os.environ.get('FACE_ID_BLINK_SCORE_DROP_THRESHOLD', '3.0'))
EMPLOYEE_SERVICE_ENABLED = _env_bool('EMPLOYEE_SERVICE_ENABLED', False)
EMPLOYEE_SERVICE_BASE_URL = os.environ.get('EMPLOYEE_SERVICE_BASE_URL', 'http://127.0.0.1:5000').strip()
EMPLOYEE_SERVICE_PUBLIC_URL = os.environ.get('EMPLOYEE_SERVICE_PUBLIC_URL', EMPLOYEE_SERVICE_PUBLIC_URL_DEFAULT).strip()
EMPLOYEE_SERVICE_API_KEY = os.environ.get('EMPLOYEE_SERVICE_API_KEY', 'dev-employee-service-key').strip()
EMPLOYEE_SERVICE_TIMEOUT = int(os.environ.get('EMPLOYEE_SERVICE_TIMEOUT', '15'))
EMPLOYEE_SERVICE_VERIFY_SSL = _env_bool('EMPLOYEE_SERVICE_VERIFY_SSL', False)
BNPZID_CLIENT_ID = os.environ.get('BNPZID_CLIENT_ID', 'tb-project').strip()
BNPZID_CLIENT_SECRET = os.environ.get('BNPZID_CLIENT_SECRET', 'dev-bnpzid-secret').strip()
