# Generated by Django 4.2 on 2026-02-23 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цеха')),
                ('boss_fullName', models.CharField(max_length=255, verbose_name='Руководитель цеха')),
            ],
            options={
                'verbose_name': 'Цех ',
                'verbose_name_plural': 'Цех',
            },
        ),
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО ответственного лица')),
                ('position', models.CharField(max_length=255, verbose_name='Должность ответственного лица')),
            ],
            options={
                'verbose_name': 'Ответственное лицо',
                'verbose_name_plural': 'Ответственные лица',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='Название цеха')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отдел',
                'db_table': 'base_section',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=255, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=255, verbose_name='Пол')),
                ('height', models.CharField(max_length=255, verbose_name='Рост')),
                ('clothe_size', models.CharField(max_length=255, verbose_name='Размер одежды')),
                ('shoe_size', models.CharField(max_length=255, verbose_name='Размер обуви')),
                ('headdress_size', models.CharField(max_length=255, verbose_name='Размер головного убора')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('date_of_employment', models.DateField(verbose_name='Дата приема на работу')),
                ('date_of_change_position', models.DateField(verbose_name='Дата последнего изменения должности')),
                ('updatedAt', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('addedUser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.department', verbose_name='Цех')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.section', verbose_name='Отдел')),
                ('updatedUser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'historical Сотрудник',
                'verbose_name_plural': 'historical Сотрудник',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=255, verbose_name='Отчество')),
                ('tabel_number', models.CharField(max_length=255, unique=True, verbose_name='Табельный номер')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=255, verbose_name='Пол')),
                ('height', models.CharField(max_length=255, verbose_name='Рост')),
                ('clothe_size', models.CharField(max_length=255, verbose_name='Размер одежды')),
                ('shoe_size', models.CharField(max_length=255, verbose_name='Размер обуви')),
                ('headdress_size', models.CharField(max_length=255, verbose_name='Размер головного убора')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('date_of_employment', models.DateField(verbose_name='Дата приема на работу')),
                ('date_of_change_position', models.DateField(verbose_name='Дата последнего изменения должности')),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('isActive', models.BooleanField(default=True)),
                ('addedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department', verbose_name='Цех')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.section', verbose_name='Отдел')),
                ('updatedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудник',
                'db_table': 'base_employee',
            },
        ),
    ]
