# Generated by Django 4.2 on 2026-02-23 09:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPEProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('renewal_months', models.PositiveIntegerField(default=0, help_text="0 bo'lsa muddat yo'q (cheklanmagan)", verbose_name='Срок обновления (в месяцах)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Средство индивидуальной защиты',
                'verbose_name_plural': 'Средства индивидуальной защиты',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_change_position',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего изменения должности'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='date_of_change_position',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего изменения должности'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField(default=datetime.datetime.now, verbose_name='Дата выдачи')),
                ('note', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='base.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_issued_docs', to=settings.AUTH_USER_MODEL)),
                ('ppeproduct', models.ManyToManyField(related_name='issues', to='base.ppeproduct', verbose_name='Средство индивидуальной защиты')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
    ]
