# Generated by Django 4.2 on 2026-02-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_ppeproduct_alter_employee_date_of_change_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='responsible_person',
            field=models.ManyToManyField(related_name='employees', to='base.responsibleperson', verbose_name='Ответственные лица'),
        ),
    ]
