# Generated by Django 4.2 on 2026-02-23 10:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_employee_responsible_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField(default=datetime.datetime.now, verbose_name='Дата выдачи')),
                ('note', models.TextField(blank=True, default='')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='base.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_issued_docs', to=settings.AUTH_USER_MODEL)),
                ('ppeproduct', models.ManyToManyField(related_name='issues', to='base.ppeproduct', verbose_name='Средство индивидуальной защиты')),
                ('responsible_person', models.ManyToManyField(related_name='employees', to='base.responsibleperson', verbose_name='Ответственные лица')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
