# Generated by Django 4.2 on 2026-02-24 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_item_delete_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='note',
        ),
        migrations.AddField(
            model_name='item',
            name='addedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='item',
            name='next_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей выдачи'),
        ),
        migrations.AddField(
            model_name='item',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='item',
            name='updatedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='ppeproduct',
            name='type_product',
            field=models.CharField(blank=True, choices=[('Комплект', 'Комплект'), ('Пора', 'Пора'), ('ШТ', 'ШТ')], max_length=255, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updatedUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_items', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
    ]
