# Generated by Django 4.2 on 2026-02-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_item_responsible_person_historicalitem_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.TextField(blank=True, null=True, verbose_name='Должность'),
        ),
    ]
