# Generated by Django 4.2 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ppe_sizes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Размеры СИЗ'),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='ppe_sizes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Размеры СИЗ'),
        ),
    ]
