# Generated by Django 4.2 on 2026-02-25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_item_ppe_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitem',
            name='issued_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='next_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей выдачи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='issued_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='item',
            name='next_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей выдачи'),
        ),
    ]
