# Generated by Django 4.2 on 2026-03-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_ppearrival_size'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS base_item_responsible_person;',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='item',
                    name='responsible_person',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='base_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Базовое фото 3x4'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='position',
            field=models.TextField(blank=True, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фото при выдаче'),
        ),
    ]
