# Generated by Django 4.2 on 2026-03-02 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0021_ppearrival_size_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingItemIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppeproduct_ids', models.JSONField(default=list, verbose_name='ID средств защиты')),
                ('ppe_sizes', models.JSONField(blank=True, default=dict, verbose_name='Размеры СИЗ')),
                ('verified_image', models.ImageField(blank=True, null=True, upload_to='pending_verified_images/', verbose_name='Фото верификации')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Подпись сотрудника')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подписи'), ('confirmed', 'Подтверждено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('confirmed_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_source', to='base.item')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_issues_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_issues', to='base.employee')),
            ],
            options={
                'verbose_name': 'Ожидающая выдача',
                'verbose_name_plural': 'Ожидающие выдачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
