# Generated by Django 4.2 on 2026-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_ppeproduct_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='requires_face_id_checkout',
            field=models.BooleanField(default=True, help_text='Если отключено, сотрудник может брать СИЗ без верификации лица', verbose_name='Требуется Face ID при выдаче СИЗ'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='requires_face_id_checkout',
            field=models.BooleanField(default=True, help_text='Если отключено, сотрудник может брать СИЗ без верификации лица', verbose_name='Требуется Face ID при выдаче СИЗ'),
        ),
    ]
