# Generated by Django 4.2 on 2026-03-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_employee_service_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppeproduct',
            name='type_product',
            field=models.CharField(blank=True, choices=[('Комплект', 'Комплект'), ('Пара', 'Пара'), ('ШТ', 'ШТ')], max_length=255, null=True, verbose_name='Единица измерения'),
        ),
    ]
