# Generated by Django 4.2 on 2026-03-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('warehouse_manager', 'Складской менеджер'), ('user', 'Обычный пользователь')], default='user', max_length=32),
        ),
    ]
