# Generated by Django 4.2 on 2026-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userrole_base_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('warehouse_manager', 'Складской менеджер'), ('warehouse_staff', 'Складской рабочий'), ('user', 'Обычный пользователь')], default='user', max_length=32),
        ),
    ]
