# Generated by Django 4.2 on 2026-03-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('warehouse_manager', 'Складской менеджер'), ('warehouse_staff', 'Складской рабочий'), ('hr', 'Отдел кадров'), ('user', 'Обычный пользователь')], default='user', max_length=32),
        ),
    ]
