# Generated by Django 4.2 on 2026-04-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rolepageaccess_face_id_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='employee_slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Slug сотрудника из employee_service'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='face_id_required',
            field=models.BooleanField(default=True, verbose_name='Требуется Face ID при входе'),
        ),
    ]
